name: Deploy to EC2
  
on:
    push:
      branches:
        - main
    workflow_dispatch:
  
jobs:
    Deployment_on_EC2:
      runs-on: ubuntu-latest
    
      steps:
      
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}
  
        
      - name: Deploying code on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@13.200.156.51 << EOF
            set -e
            export PATH=$PATH:/usr/bin:/usr/local/bin                                          
            cd /home/ubuntu/pi-sectheta-website
            git branch
            git pull https://github.com/panacea-infosec/pi-sectheta-website
            npm -v
            npm install
            cd /home/ubuntu
            ./restart.sh
            sudo systemctl reload nginx 
          EOF
    
